### ISSUE TITLE
`node-uuid` has been deprecated

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/rails-erb-loader#11]
User `uuid` instead. https://www.npmjs.com/package/uuid

**Comment by rhys-vdw** [comment]
I wonder if we wouldn't be fine just replacing this feature with a constant:

```
const delimeter = '__RAILS_ERB_LOADER__'
```

**Comment by jdlehman** [comment]
That constant is probably sufficient. I think it is highly unlikely that the delimiter is included in any JS files.

**Comment by guilleiguaran** [comment]
👍 the constant is good enough.
