### ISSUE TITLE
`child.stdin` is undefined in some circumstances

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/rails-erb-loader#2]
```
10:31:45 webpack.1 | ERROR in ./app/assets/javascripts/views/screenshot-hitzone-editor.js.erb
10:31:45 webpack.1 | Module build failed: TypeError: Cannot read property 'write' of undefined
10:31:45 webpack.1 |     at Object.module.exports (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/uh-erb-loader/index.js:20:14)
10:31:45 webpack.1 |  @ ./app/assets/javascripts/components/test-form/screenshots-editor/screenshots-editor.js 71:31-82
10:31:45 webpack.1 | 
10:31:45 webpack.1 | ERROR in ./app/assets/javascripts/constants/screenshot-image-types.js.erb
10:31:45 webpack.1 | Module build failed: TypeError: Cannot read property 'write' of undefined
10:31:45 webpack.1 |     at Object.module.exports (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/uh-erb-loader/index.js:20:14)
10:31:45 webpack.1 |  @ ./app/assets/javascripts/components/test-form/screenshots-editor/screenshots-editor.js 99:28-80
```

Coming from [here](https://github.com/usabilityhub/erb-loader/blob/9bc50a6f5552ba53937b56052539621b8b3e43bb/index.js#L20).

Apparently `child.stdin` is undefined in some circumstances. It's unclear to me how this could occur.

Have you seen this one @jdlehman? It's only coming up occasionally.

**Comment by rhys-vdw** [comment]
According to the reference for [child.stdin](https://nodejs.org/api/child_process.html#child_process_child_stdin):

> If the child was spawned with stdio[0] set to anything other than 'pipe', then this will be undefined.

**Comment by jdlehman** [comment]
No this is the first time I have seen this. Maybe we should try `child_process.spawn` instead of `child_process.exec`?

**Comment by rhys-vdw** [comment]
I'm hitting this problem constantly today since updating a bunch of dev dependencies. Triggering another compile seems to fix the problem.

Seems like the main difference between `spawn` and `exec` is that `exec` has the possibility of failing if a file exceeds `maxBuffer` (set to 200KB by default). `exec` makes life easier by offering a single callback with the entire output (which is what we want to then regex and pass back to webpack). Might be worth looking into...

I do wonder if I'm hitting some weird Node bug though. Nobody else on my team has hit it yet...

**Comment by rhys-vdw** [comment]
Well, it hasn't come up again so I'm closing this issue for now.

**Comment by rhys-vdw** [comment]
Just saw this again:

```
14:28:25 webpack.1 | /Users/rhys/Projects/usability-hub/erb-loader/index.js:72
14:28:25 webpack.1 |   child.stdin.on('error', function (error) {
14:28:25 webpack.1 |              ^
14:28:25 webpack.1 |
14:28:25 webpack.1 | TypeError: Cannot read property 'on' of undefined
14:28:25 webpack.1 |     at transformSource (/Users/rhys/Projects/usability-hub/erb-loader/index.js:72:14)
14:28:25 webpack.1 |     at /Users/rhys/Projects/usability-hub/erb-loader/index.js:146:7
14:28:25 webpack.1 |     at /Users/rhys/Projects/usability-hub/erb-loader/index.js:112:30
14:28:25 webpack.1 |     at FSReqWrap.oncomplete (fs.js:123:15)
14:28:25 webpack.1 | error Command failed with exit code 1.
```

**Comment by rhys-vdw** [comment]
Been over a year now.
