### ISSUE TITLE
Support WebPack 2

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/rails-erb-loader#23]
I'm not sure exactly what's required (if anything), but it would be good to update to support WebPack 2.

**Comment by guilleiguaran** [comment]
I'll investigate but I'm pretty sure this is working fine since we migrated webpacker to WebPack2 weeks ago and we haven't received any issue report related to rails-erb-loader.

**Comment by rhys-vdw** [comment]
That's good to hear @guilleiguaran.

- [ ] README need to be updated to [use `rules:` instead of `preLoaders:`](https://webpack.js.org/guides/migrating/#module-preloaders-and-module-postloaders-was-removed).

- [ ] `options` are now [nested beneath the loader config, instead of at the root level](https://webpack.js.org/guides/migrating/#loader-configuration-is-through-options). This should be demonstrated in the README.

- [ ] `cacheable` is now [on by default](https://webpack.js.org/guides/migrating/#cacheable), so that option should be broken.

There may be other points in the [migration guide](https://webpack.js.org/guides/migrating/), but sounds like it's not urgent.
