### ISSUE TITLE
Use `child_process.execFile`

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/rails-erb-loader#36]
Instead of `child_process.exec`.

> The child_process.execFile() function is similar to child_process.exec() except that it does not spawn a shell. Rather, the specified executable file is spawned directly as a new process making it slightly more efficient than child_process.exec().

https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

**Comment by a3ammar** [comment]
Hi,
To change to `execFile` would mean we must change the `runner` option from `bin/rails runner` to `bin/rails` and then add the `runner` part as an argument to `execFile`. This would break webpacker since they [explicitly set the runner option](https://github.com/rails/webpacker/blob/f0bae366b539b1d6f798f1050e5e13fa51003e7f/lib/install/config/loaders/core/erb.js).

So, should we keep compatibility by processing the `runner` string or make a breaking change?

**Comment by rhys-vdw** [comment]
Firstly, it's not super important to make this change. I just discovered the API and thought it was more appropriate. The docs say it's only "slightly more efficient".

I think processing the runner string would be most appropriate, since supplying a single string seems to easiest option for the consumer.

We could do something like:

```js
const [runner, ...args] = options.runner.split(' ')
const child = execFile(runner, [...args, transformerPath, ioDelimeter, engine], callback)
```

Would be less pretty since this repo still supports Node 0.10 for now (unless we started transpiling with Babel, but that's a lot of work for no real change).

**Comment by rhys-vdw** [comment]
btw if you'd like to make this change, @a3ammar, you're quite welcome. :)

**Comment by a3ammar** [comment]
I'd like to take a crack at it but first I'd like to understand why runner is a passable option in the first place. Is there another way to run Ruby code in Rails' context without using `rails runner`? Or is it an option to avoid using the stub?

**Comment by a3ammar** [comment]
Also, I'm not sure about the contribution process, should I make a PR or push to a branch?

**Comment by rhys-vdw** [comment]
> I'd like to take a crack at it

Cool. :)

> I'd like to understand why runner is a passable option in the first place.

Setting `runner` to `ruby` allows you to run Ruby code _outside_ of the Rails context, for non-rails projects. You can see an example [here](https://github.com/usabilityhub/rails-erb-loader/blob/d97a732844f612e83be14489b6901a17e78facfd/README.md#configuration).

> should I make a PR or push to a branch?

You can make a branch either in your fork, or in this repository (since you're a collaborator). When you're ready open a PR in this repository from your branch. Please lint the project (`npm run lint`) before opening the PR to make sure that it's conforming to our ESLint config.
