### ISSUE TITLE
Webpack 3 support

### ISSUE THREAD

**Issue by renchap** [usabilityhub/rails-erb-loader#40]
PeerDependancies needs to be updated to allow the brand new  [Webpack 3](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b).

Other changes might be needed as the internals have moved a bit.

**Comment by rhys-vdw** [comment]
Thanks @renchap. Happy to take a PR or I'll get around to it in the coming days.

**Comment by rhys-vdw** [comment]
Closed by #41

**Comment by rhys-vdw** [comment]
Hey @renchap you can use 5.1.0 for Webpack 3 support now.
