### ISSUE TITLE
Can't test files that import .js.erb

### ISSUE THREAD

**Issue by K1N5L4Y3R** [usabilityhub/rails-erb-loader#48]
I have a file app/javascript/packs/components/module_one.js which I'm trying to test with Jest. This file contains an import to an .js.erb file as follows:

```
// app/javascript/packs/components/module_one.js

import ModuleTwo from './module_two.js.erb'

// ...
```

module_two.js.erb contains the following:

```
// app/javascript/packs/components/module_two.js.erb

import ModuleOne from './module_one'

// ...
```

While running webpack-dev-server everything works as expected, but when I try to run `yarn test`, it complains with the following error:

```
FAIL  app/javascript/test/module_one.test.js
  ● Test suite failed to run

    /path/to/module_two.js.erb:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import ModuleOne from './module_one'
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:306:17)
      at Object.<anonymous> (app/javascript/packs/components/module_one.js:1:745)
      at Object.<anonymous> (app/javascript/test/module_one.test.js:1:124)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.545s
Ran all test suites.
error Command failed with exit code 1.
```

So it seems like the module_two.js.erb file is not being transformed properly from ES6, because when I remove the first line of module_one.js, it doesn't complain anymore.

Here is my current setup:

```
// .babelrc

{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    ["transform-class-properties", { "spec": true }]
  ],

  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```

```
// package.json

{
  // ...
  "devDependencies": {
    "babel-jest": "^21.0.2",
    "jest": "^21.0.2",
    "regenerator-runtime": "^0.11.0",
    "webpack-dev-server": "^2.7.1"
  },
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "roots": [
      "<rootDir>/app/javascript/test"
    ],
    "moduleDirectories": [
      "<rootDir>/node_modules"
    ],
    "moduleFileExtensions": [
      "js",
      "jsx",
      "erb"
    ],
    "transform": {
      "^.+\\.jsx?$": "babel-jest",
      "ˆ.+\\.jsx?.erb": "rails-erb-loader"
    }
  }
}
```

I apologize in advance if this is not the right place for this issue. Any help will be appreciated.

**Comment by rhys-vdw** [comment]
Hey @K1N5L4Y3R.

Would I be right in thinking that the `transform` key in your `package.json` is being read by Babel?
 `rails-erb-loader` is a webpack plugin, so I'm not sure how it works. (After some googling I found [its documentation](https://facebook.github.io/jest/docs/en/configuration.html#transform-object-string-string) - look like this should work).

Other observations:

```js
    "transform": {
      "^.+\\.jsx?$": "babel-jest",
      "ˆ.+\\.jsx?.erb": "rails-erb-loader"
    }
```

One of these regexes starts with `^`, the other starts with `ˆ`. I don't know what the latter is - it looks like an accent character as opposed to a caret. That's not the regex you want.

```js
      "^.+\\.jsx?$": "babel-jest",
```

So you still need to transpile from ES6 to a version of JavaScript that will run. This regex doesn't match your erb files, so they'll only be transpiled by erb-loader.

You would need something like this:

```js
    "transform": {
      "\\.jsx?(\\.erb)?$": "babel-jest",
      "\\.erb$": "rails-erb-loader"
```

(You can try these regexes out in [regex101](https://regex101.com/) if you don't understand how they work)

In webpack these are run from bottom to top, so this would be correct. (ie. first transpile erb -> ES6, then transpile ES6 -> ES5). I'm not sure about jest, but you could try swapping them around if that doesn't work.

Anyway, from the sound of things I don't think this is a problem with rails-erb-loader so I'm closing the issue. Let me know if I'm mistaken. Good luck. :)
