### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/rails-erb-loader#5]
I originally prefixed this with "uh" hastily to avoid a name collision with the existing [erb-loader](http://npmjs.com/erb-loader). However it's inappropriate and confusing to reference UsabilityHub in this loader's name.

I'm thinking we should go with `rails-erb-loader` and also try to get it added to the official [list of loaders](https://webpack.github.io/docs/list-of-loaders.html).

**Comment by jdlehman** [comment]
👍 to `rails-erb-loader` as it does assume a Rails project since `rails runner` is used

**Comment by rhys-vdw** [comment]
Cool, all done. :) Also I added it to the [list of loaders](https://github.com/webpack/docs/wiki/list-of-loaders#templating).
