### ISSUE TITLE
Using rails-erb-loader from CSS @import?

### ISSUE THREAD

**Issue by mikebaldry** [usabilityhub/rails-erb-loader#51]
I'm sharing global variables (brand colours, etc) from my rails code, to a `settings.scss.erb` in the asset pipeline - I want to include this in to a Vue components styling but I can't seem to get it to process the ERB file - it just doesn't get parsed through this package.

I've added the rule to my webpack config. 

Any idea what I'm doing wrong?

**Comment by rhys-vdw** [comment]
Ah yeah, I had problems with this too. It works okay if you import via `require()` in JS but not via scss-loader (which I assume you're using). I think that scss-loader doesn't resolve `@import`ed file contents via webpack, but that's an issue you'll have to take up there. (I actually spent time time trying to fix this myself).

I can recommend another approach that works quite nicely though: [`sass-values-loader`](https://www.npmjs.com/package/sass-values-loader), made by @monvillalon to address this very issue. This will only help with inter-operation between JS and CSS though so it may not be exactly what you want.

**Comment by rhys-vdw** [comment]
Closing because it's not a problem with `rails-erb-loader`. Good luck!

**Comment by mikebaldry** [comment]
Thanks for the response, makes sense 👍
