### ISSUE TITLE
Module build failed with .vue.erb files

### ISSUE THREAD

**Issue by akaspick** [usabilityhub/rails-erb-loader#58]
Not sure where the following error came from as I was deploying regularly and then nope..

This error only seems to occur with .vue.erb files.  It appears to be an issue with the erb loader though as that seems to be the point where the compilation fails.

My package.json
```
{
  "dependencies": {
    "@rails/webpacker": "^3.2.2",
    "caniuse-lite": "^1.0.30000697",
    "css-loader": "^0.28.10",
    "rails-erb-loader": "^5.2.1",
    "vue": "^2.5.13",
    "vue-loader": "^14.1.1",
    "vue-template-compiler": "^2.5.13",
    "webpack": "^3.10.0",
    "webpack-merge": "^4.1.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.11.1"
  }
}
```

And the error which only occurs for two (I only have two) of my .vue.erb files.
```
ERROR in ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-62bbf8aa","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./node_modules/rails-erb-loader??ref--5-0!./app/javascript/packs/public/sections.vue.erb
       Module build failed: Error: Command failed: bin/rails runner /home/deploy/myapp/tmp/build-152020830820117/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb 0

           at ChildProcess.exithandler (child_process.js:199:12)
           at emitTwo (events.js:106:13)
           at ChildProcess.emit (events.js:191:7)
           at maybeClose (internal/child_process.js:920:16)
           at Socket.<anonymous> (internal/child_process.js:351:11)
           at emitOne (events.js:96:13)
           at Socket.emit (events.js:188:7)
           at Pipe._handle.close [as _onclose] (net.js:509:12)
        @ ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-62bbf8aa","scoped":true,"sourceMap":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./node_modules/rails-erb-loader??ref--5-0!./app/javascript/packs/public/sections.vue.erb 4:14-425
        @ ./app/javascript/packs/public/sections.vue.erb
```

I've researched and looked for possible reasons for the failure for hours and nothing resolves the issue.  I don't understand the error message, so I'm at a loss on what exactly the issue might be.

**Comment by rhys-vdw** [comment]
Hi @akaspick, sorry to hear about this issue. Currently `stderr` output is suppressed. You might get more information by adding a line [here](https://github.com/usabilityhub/rails-erb-loader/blob/80d87fb3095a5d15d1f7aa72471c6db998281296/index.js#L94):

```js
console.log("ERROR: " + stderr);
```

Otherwise we should get better error handling when #56 is wrapped up. Still a bit of work to go there atm.

**Comment by akaspick** [comment]
Thanks @rhys-vdw, I upgraded rails-erb-loader to 5.3.0 and added the console statement, but nothing appeared.  The latest error is shown below, but it looks almost the same as the previous one with only minor differences.

```
ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-62bbf8aa","hasScoped":true,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/template-compiler/preprocessor.js?engine=slm!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./node_modules/rails-erb-loader??ref--7-0!./app/javascript/packs/public/sections.vue.erb
Module build failed: Error: Command failed: bin/rails runner /home/deploy/myapp/releases/342/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
 @ ./app/javascript/packs/public/sections.vue.erb 8:0-463
```

**Comment by akaspick** [comment]
@rhys-vdw Not sure if it helps, but everything compiles fine in my development environment, but not on my production server.  Is there anything worth looking into regarding the environment?

**Comment by akaspick** [comment]
@rhys-vdw Looks like the issues lies with webpacker.  Notably https://github.com/rails/webpacker/issues/1222

I'll close this, but improved error messages from rails-erb-loader would be helpful.  Thanks for trying to help.  When there are so many parts working together, it's difficult to figure out where the issue lies.

**Comment by rhys-vdw** [comment]
@akaspick So what exactly was going wrong here? What would have been an appropriate error message? (I haven't used webpacker)

**Comment by akaspick** [comment]
@rhys-vdw I was deploying to a staging environment and webpacker currently doesn't handle non-standard environments well.  webpacker was failing, but the error was showing rails-erb-loader as the source of the issue.  Perhaps it's a webpacker logging issue instead... I'm really not sure.  Overall, the error message I was seeing was not really pointing me in any obvious direction.

Thanks for checking in though.

**Comment by rhys-vdw** [comment]
Okay. If you find out what the specific issue is (eg. `bin/rails` did not exist) then we might be able to add an explicit check that the executable exists and give a better warning.

**Comment by akaspick** [comment]
@rhys-vdw Update.  I ran into more issues again and everything worked when I removed erb-helper from the compilation steps.  Turns out me upgrading to node 8.9.4 from 6.13.0 resolved my issues (minus a separate webpacker issue).

**Comment by rhys-vdw** [comment]
Thanks for the update @akaspick.

> I removed erb-helper from the compilation steps

What is erb-helper?

**Comment by akaspick** [comment]
@rhys-vdw Sorry, I meant rails-erb-loader.
