### ISSUE TITLE
Support webpack 4

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/rails-erb-loader#59]
Add webpack 4 to tests and update peerDependency.

**Comment by n-rodriguez** [comment]
It already works here but it would be great to have tests :)

**Comment by rhys-vdw** [comment]
Absolutely. Feel free to open a PR, @n-rodriguez. At the moment I don't have much time to dedicate to rails-erb-loader.

**Comment by rhys-vdw** [comment]
(FYI we're also using webpack 4 without issue)

**Comment by PikachuEXE** [comment]
Just do similar thing to 
https://github.com/usabilityhub/rails-erb-loader/blob/master/package.json#L13

Off topic: Should we set up Travis or other CI for this project?

**Comment by rhys-vdw** [comment]
@PikachuEXE Yep: #42

**Comment by n-rodriguez** [comment]
Hi there! Any news?
