### ISSUE TITLE
Unable to supply environment variables in `runner` argument.

### ISSUE THREAD

**Issue by rhys-vdw** [usabilityhub/rails-erb-loader#64]
Reported by @dreyks [here](https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-381112052).

>
> > `options: { runner: 'DISABLE_SPRING=1 bin/rails runner' }`
>
> I tried this for other ENV var that i needed and this does not work. parseRunner splits by spaces so the ENV var becomes a file that spawn tries to call

Rather than improving the support for `runner` string, I think something like this would be most appropriate for the internal usage of [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options).

```js
options: {
  runner: {
    path: 'bin/rails',
    args: ['runner'],
    env: {
      ...process.env,
      DISABLE_SPRING: 1,
    }
  }
}
```

NOTE: When supplying `options.env` to `spawn` it will override the default of passing `process.env`, so this must be explicitly provided by config. This additionally provides the option of passing `{}` to prevent this default behaviour.

**Comment by PikachuEXE** [comment]
I got a different issue (I think ruby hangs with spring enabled while compiling)
"fixed" by disabling spring in `bin/rails` but not really a good change
So +1 for this proposal

Maybe I will open a PR for making this change later

**Comment by rhys-vdw** [comment]
@PikachuEXE yeah, that's be great. It's a pretty trivial change I think.

Btw the problem you're experiencing with spring is #47, which has been very hard to pin down. I guess I should reopen it.

**Comment by PikachuEXE** [comment]
Please take a look at #70
