### ISSUE TITLE
Config: Testing for Windows doesn't work when using a Linux subsystem

### ISSUE THREAD

**Issue by jonhue** [usabilityhub/rails-erb-loader#67]
I am compiling with webpack in the Ubuntu subsystem of Windows. This is my generated erb-loader config:

```js
module.exports = {
  test: /\.erb$/,
  enforce: 'pre',
  exclude: /node_modules/,
  use: [{
    loader: 'rails-erb-loader',
    options: {
      runner: (/^win/.test(process.platform) ? 'ruby ' : '') + 'bin/rails runner'
    }
  }]
}
```

The problem is here: `runner: (/^win/.test(process.platform) ? 'ruby ' : '') + 'bin/rails runner'`.
While this works in Windows, it does not in the subsystem as it does not recognize it as Windows.

Replacing the runner option with `runner: 'ruby bin/rails runner'` solves the problem locally but breaks production on a linux server.

Is there a way I can distinguish development from production?

**Comment by jonhue** [comment]
`process.platform` returns `linux` in the Linux subsystem.

**Comment by rhys-vdw** [comment]
Sure, just test `process.env.NODE_ENV` instead. I assume the config you're sharing is from webpacker?

**Comment by jonhue** [comment]
That's what I ended up doing for now. But it's not great if you develop on multiple machines with on being Unix based and one being Windows.
Is there a way to test directly for the required command?

**Comment by rhys-vdw** [comment]
Just to be clear - rails-erb-loader does nothing smart with the runner command at present. Since the loader doesn't require rails (can use ruby directly) I don't think there's a way to generalize.

Perhaps a solution like this makes sense:

```js
module.exports = {
  test: /\.erb$/,
  enforce: 'pre',
  exclude: /node_modules/,
  use: [{
    loader: 'rails-erb-loader',
    options: {
      // Set this in each environment.
      runner: process.env.RAILS_ERB_LOADER_RUNNER,
    }
  }]
}
```

Just for my curiosity: Why is it that `bin/rails runner` fails in the Linux subsystem? Is it not executable?

**Comment by jonhue** [comment]
That happens because even though I am using the Linux subsystem, my Ruby installation is mingw (because the subsystem still uses the Windows kernel).

**Comment by rhys-vdw** [comment]
I'm going to close this one because I think the per-platform runner is probably the best solution there. If you can think of a way to detect that webpack is running on the Linux subsystem I'd suggestion raising an issue with `webpacker` that changes their config template.

**Comment by jonhue** [comment]
Ok, thank you!

**Comment by rhys-vdw** [comment]
Hey @jonhue if you do find a nice solution you're invited to tackle #52. It wont make a difference in the case of webpacker though since it's overriding the defaults. Perhaps if #52 is closed the webpacker default runner could be set to `undefined` so it just takes the default from this project.
