### ISSUE TITLE
Using ruby as a runner for erb template

### ISSUE THREAD

**Issue by valterbarros** [usabilityhub/rails-erb-loader#68]
**rails version 5.2.0
ruby version 2.5.1**

Hello guys I see in your documentation about this to use ruby like runner:
```
{
  loader: 'rails-erb-loader',
  options: {
    runner: 'ruby',
    engine: 'erb'
  }
}
```

And I'm working on a rails project that use i18n inside coffee.erb to translate, the problem is when I use rails like runner the compiling from webpack is a bunch of slow, and when I use ruby I get this error.

```
Traceback (most recent call last):
	3: from /home/thevalter/Documents/projects/stant/node_modules/rails-erb-loader/erb_transformer.rb:19:in `<main>'
	2: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/erb.rb:876:in `result'
	1: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/erb.rb:876:in `eval'
(erb):52:in `<main>': uninitialized constant I18n (NameError)
```

Someone can help me?

**Comment by rhys-vdw** [comment]
(sorry about the TypeScript)

**Comment by valterbarros** [comment]
this Is a nice workaround

**Comment by valterbarros** [comment]
> In our system we actually dump the translations from the server into a <script /> 

You dump the .yml files inside a script tag? 

Sorry i'm not used with typescript and lodash, can you explain about this function? 

```
return reduce(
    interpolations,
    (result, value, key) => result.replace(`%{${key}}`, value),
    translation
  )
```

> console.log(translate(en, "greetings.hello"))

This `console.log` will return the result from "grettings.hello" or you replace the value from `${key}` pattern by "grettings.hello"?

**Comment by rhys-vdw** [comment]
We set the correct language by calling `I18n.with_locale` in the controller before calling the `include_paths` function. The reason we made `include_paths` is because we don't need all of the translations, but you could modify it to just include everything.

**Comment by rhys-vdw** [comment]
We could probably wrap this up into a library really...

**Comment by rhys-vdw** [comment]
Hey feel free to ask more questions, but I'm going to close the issue because it's not actionable on our end.

**Comment by valterbarros** [comment]
@rhys-vdw Ok man closes this issue. I like all your solution and I'm going to apply in my project. I need only take a time to understand all code and if I have some doubt I'll ask to you. Thanks a lot. For while I'm continue using the `rails-erb-loader` that is too a good solution. :smile:

**Comment by valterbarros** [comment]
And I agree with the option for wrap this solution in a library

**Comment by valterbarros** [comment]
Heey man good news, I tried your solution to dump the locales inside html and use js script to read and replace on code and work very well, Man thanks so much you save my project. :grinning:. I had 51 coffee.erb files and compile theses was a big problem for me now is no more.

**Comment by valterbarros** [comment]
With this the webpack's compile time was decrease form **184000ms** to **9000ms**

**Comment by rhys-vdw** [comment]
Oh awesome! 😃

**Comment by valterbarros** [comment]
[update] I added a modification to increase quality from conversion from locale object that was put the data inside a data attribute, because put in value from script gave a error something like `unexpected .`

` <script id="translations" data-content="<%= JSON.generate(i18n_paths(".")) %>">`
