### ISSUE TITLE
Few invisible symbols

### ISSUE THREAD

**Issue by bragovo** [usabilityhub/rails-erb-loader#74]
I use erb loader for this https://github.com/fnando/i18n-js
```
I18n = {}
I18n.translations = <%= I18n::JS.filtered_translations.to_json %>;
console.log(I18n.translations);
```
In random places I found symbols like this:`"sure": "Уверен��?",`.
When I print `<%= I18n::JS.filtered_translations.to_json %>` without loader (plain rails) — JSON fine `"sure":"Уверены?"`.

It depends of yml file size. Short file — no symbols, large file — a lot of. Maybe it's because webpack 4.x, I using same method on projects with 3.x version and everything fine there. Seems problem https://github.com/usabilityhub/rails-erb-loader/blob/master/index.js#L109 (or in runner), because when I insert `var matches = dataBuffers.join(' ZZ ').match(sourceRegex)` result will be `"Уверен� ZZ �?"` like if it's split multibyte letter.

Or it's maybe problem with i18n-js?

**Comment by rhys-vdw** [comment]
Interesting. We also use I18n but not via rails-erb-loader. I've detailed our approach in #68. 

I don't know off hand what the issue is, but you should be able to inspect the output in your browser to check whether the problem is in the output of rails-erb-loader or in i18n-js.

**Comment by bragovo** [comment]
I created example repo https://github.com/bragovo/erb-loader-in18-js
`"signed_out": "Выход из системы ��ыполнен."` — that's wrong string.
If you delete 313 & 314 rows from this file https://github.com/bragovo/erb-loader-in18-js/blob/master/config/locales/ru.yml#L313 JS compile fine.

In Gemfile you can uncomment faker gem and compile again and a lot of this error will be appears.

I don't know how to find problem. Everything I can found it's problems in places when buffers join('') in one string and only for utf8 characters (no errors with english). But if only 2 or 3 buffers no errors, but 4-5 or more in every places where buffers join('').

**Comment by rhys-vdw** [comment]
Hm, sorry for the inactivity on this one. To be honest I just won't have the time to address this... Could [this](https://mathiasbynens.be/notes/javascript-unicode#reversing-strings) be a clue?

I wonder if we can join the strings in a `Buffer` instead of with `strings.join` for it to work? I'm pretty stumped sorry.

Are you using the latest version of Node?

**Comment by rhys-vdw** [comment]
Note: https://nodejs.org/api/string_decoder.html might help

**Comment by rhys-vdw** [comment]
Also it's possible to set the encoding to utf-16 via spawn options.

**Comment by bragovo** [comment]
Thank you, but these solutions didn't help me. But I found solution here https://github.com/nodejs/help/issues/1302#issuecomment-392460004
I create PR https://github.com/usabilityhub/rails-erb-loader/pull/77
